import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation/Nagivation";
import { CartCountProvider } from "./components/cart/cartCountContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}; // #Blackmagic

export const experimental_ppr = true;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} w-screen h-screen`}>
				<CartCountProvider>
					<Navigation />
					{children}
				</CartCountProvider>
			</body>
		</html>
	);
}
